python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
# command to install dependencies
install:
  - pip3 install numpy
  - pip3 install scipy
  - pip3 install scikit-learn
  - pip3 install cython
  - pip3 install cythongsl
  - sudo apt-get install libopenmpi-dev
  - pip3 install mpi4py
  - pip3 install pathos
  - pip3 install h5py
  - cd cosmic_profiles
  - python3 setup.py build_ext --inplace 
  - cd ..
  - python3 setup.py install
# command to run tests
script: 
  - pytest -v --cov=cosmic_profiles
