package:
  name: "cosmic_profiles"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/tibordome/cosmic_profiles

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - cython
    - cythongsl
    - mpi4py
    - openmp
    - openmpi=4.1.2
    - pathos
    - h5py

about:
  home: https://github.com/tibordome/cosmic_profiles
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Implements 3D point cloud algorithms for estimation and fitting of shape and density profiles "

extra:
  recipe-maintainers:
    - tibordome
