channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20.3
  - scipy
  - mpi4py
  - h5py
  - matplotlib
  - scikit-learn
  - pathos
  - cython
  - psutil
  - sphinx-autoapi
  - sphinx_rtd_theme=1.0.0
  - twine
  - pip:
    - sphinx_design
