channels:
  - conda-forge
  - bccp
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20.3
  - scipy
  - mpi4py
  - h5py
  - matplotlib
  - scikit-learn
  - cython
  - sphinx-autoapi
  - sphinx_rtd_theme
  - nbodykit
  - twine
  - pip>=20.1
  - pip:
    - pynverse==0.1.4.4
    - pynbody
